### PR TITLE
Case insensitive delete

### LINKED ISSUE #145: Delete command - Make name case insensitive

### PR DESCRIPTION
**Pull request by wapisai**
# This PR addresses the issues #145 
fix #145 
This Pull Request makes Delete command case insensitive for names

### Changes Made:
- Use parseNameReturnStored for DeleteCommandParser so names are case insensitive

### Compatibility Assurance: 
Verified the new feature's compatibility with existing commands and functionalities through detailed automated regression testing, ensuring no disruptions to the current system.

### Code Quality Maintenance: 
Conducted thorough code quality checks to uphold our commitment to high standards and adherence to the project's coding conventions.

### Additional Notes:
Priority for this feature has been set to Medium, reflecting its importance to user experience.
We encourage further review and testing from the community to refine and validate the new tests and functionalities introduced.

### Please feel free to provide feedback or suggestions for further improvements!

### CODE REVIEW

**Review by appleraincoat — APPROVED** [review]
LGTM

**Comment by jyztintan** [comment]
Actually, can clarify the purpose of this PR?
Delete by name already seems to be case-insensitive and the parser methods look like they are doing the same things in the modification..

**Comment by wapisai** [comment]
> Actually, can clarify the purpose of this PR? Delete by name already seems to be case-insensitive and the parser methods look like they are doing the same things in the modification..

It wasnt previously?

**Comment by UdhayaShan1** [comment]
Thanks but I don't think PR is necessary now, it currently is case-insensitive, `ParseName` currently capitalises all names by itself.

**Pull request closed without merging**
